### ISSUE TITLE
Create Packet Header Parser for Flow Record Type 1-0-1

### ISSUE THREAD

**Issue by robinje** [robinje/sflow-collector#12]
The Raw Packet Heard Record type has a lot of useful information which is not being parsed out. A simple Ethernet & IPv4 parser should be relatively low effort and will significantly improve the quality of the data being extracted via sFlow.

**Comment by SeanAshford** [comment]
Just for you:
class sFlowRawPacketHeader():
    "flowData: enterprise = 0, format = 1"

    def __init__(self, length, dataGram):
        self.len = length
        self.data = dataGram
        self.headerProtocol = unpack('>i', dataGram[0:4])[0]
        self.frameLength = unpack('>i', dataGram[4:8])[0]
        self.payloadRemoved = unpack('>i', dataGram[8:12])[0]
        self.headerSize = unpack('>i', dataGram[12:16])[0]
        self.header = dataGram[(16):(16 + self.headerSize)] 
        #Need a class for parsing the header information.
        ofset=0
        self.type = unpack('>H',dataGram[36:38])[0]
        if self.type == int(16384): #if 802.1q info in sample header
            ofset=4
        self.srcMAC = hexlify(dataGram[22:28])
        self.dstMAC = hexlify(dataGram[16:22])
        self.srcIp = inet_ntop(AF_INET, dataGram[46-ofset:50-ofset])
        self.dstIp = inet_ntop(AF_INET, dataGram[50-ofset:54-ofset])
        self.srcPort = unpack('>H', dataGram[54-ofset:56-ofset])[0]
        self.dstPort = unpack('>H', dataGram[56-ofset:58-ofset])[0]

**Comment by SeanAshford** [comment]
and a bit to test it with :
if sFlowData.samples[i].records[j].format == 1 and sFlowData.samples[i].records[j].enterprise == 0:
                    records = sflow.sFlowRawPacketHeader(sFlowData.samples[i].records[j].len, sFlowData.samples[i].records[j].data)
                    print ("Raw Packet Header Protocol:", records.headerProtocol)
                    print ("Frame Length:", records.frameLength)
                    print ("Payload Removed:", records.payloadRemoved)
                    print ("Header Size:", records.headerSize)
                    MACfrom = records.srcMAC.decode("utf-8")
                    MACfrom = ':'.join(MACfrom[i : i + 2] for i in range(0, 11, 2))
                    print ("SrcMac:",MACfrom)
                    MACto = records.dstMAC.decode("utf-8")
                    MACto = ':'.join(MACto[i : i + 2] for i in range(0, 11, 2))
                    print ("DstMAC:",MACto)
                    print ("srcIp:",records.srcIp)
                    print ("dstIp:",records.dstIp)
                    print ("srcPort:",records.srcPort)
                    print ("dstPort:",records.dstPort)
                    print ('Len:',records.len)
                    print ('Type:',records.type)

**Comment by robinje** [comment]
Resolved by @SeanAshford
