### ISSUE TITLE
sFlow Packet Header Incorrect IP Address Parsing

### ISSUE THREAD

**Issue by javierBF97** [robinje/sflow-collector#30]
Hello, I am testing your sflow-collector and I have noticed that the srcIP and dstIP from sFlowRawPacketHeader() class is not allways well obtained.
For the test I am using mininet and doing a ping from Host 1: 10.0.0.1 to Host 2: 10.0.0.2 and the obtained IPs in the collector are '92.8.200.255' & '254.78.51.78'. I have checked the sflow package using wireshark to confirm that the IPs contained in the packet are '10.0.0.1' and '10.0.0.2'.
I have observed that sometimes the IPs are obtained correctly, but most of the time it does not.

regards

**Comment by robinje** [comment]
@SeanAshford do you want to take a look at this?

**Comment by robinje** [comment]
@javierBF97 I just finished a significant re-work of the code. Please evaluate the code from the refactor branch / PR #27 to ensure that it addresses this issue.

**Comment by robinje** [comment]
I took a look at the code, the header is being extracts properly. The parsing is limited to Ethernet with IPv4, that will need to be addressed as well.

**Comment by robinje** [comment]
The code in the refactor branch has been updated to address greater than the functionality intended in the Release 0.1 code for the Raw Packet Header.

**Comment by javierBF97** [comment]
I have just tested #27 this time I have used hping3. The collector sampled 1497 packets, all of them with correct source and destination IP address.

Although the code throws errors when executing the first time:
```
self.destination_mac = self.header[0:6].hex("-")
TypeError: hex() takes no arguments (1 given)
```
After removing the "-" it works fine.

**Comment by robinje** [comment]
The separator was added in 3.8.  Is it important that we continue to support 3.6 and 3.7?
